### ISSUE TITLE
undefined method `helper_method' for ActionController::API

### ISSUE THREAD

**Issue by rainerborene** [palkan/rubanok#10]
I got this message after upgrading to the latest version (it's an easy fix though):
```
/home/vmbox/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rubanok-0.2.0/lib/rubanok/rails/controller.rb:12:in `block in <module:Controller>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
```
Just need to check if class `respond_to?(:helper_method)` before adding those helpers.

**Comment by palkan** [comment]
Thanks for catching this!

Fixed and released in 0.2.1
